In [48]:
import dukascopy_python
from dukascopy_python.instruments import INSTRUMENT_FX_MAJORS_EUR_USD
import datetime
import pandas as pd

df = dukascopy_python.fetch(
    INSTRUMENT_FX_MAJORS_EUR_USD,
    dukascopy_python.INTERVAL_MIN_15,
    dukascopy_python.OFFER_SIDE_BID,
    datetime.datetime(2024,1, 1),
    datetime.datetime(2024, 6, 1)
)
df.head()

INFO:DUKASCRIPT:current timestamp :2024-01-30T19:15:00
INFO:DUKASCRIPT:current timestamp :2024-02-28T16:30:00
INFO:DUKASCRIPT:current timestamp :2024-03-28T13:30:00
INFO:DUKASCRIPT:current timestamp :2024-04-26T12:45:00
INFO:DUKASCRIPT:current timestamp :2024-05-27T12:15:00

                              open     high      low    close  volume
timestamp
2024-01-01 22:00:00+00:00  1.10427  1.10433  1.10423  1.10431  274.55
2024-01-01 22:15:00+00:00  1.10430  1.10434  1.10420  1.10430  143.55
2024-01-01 22:30:00+00:00  1.10431  1.10437  1.10431  1.10433  163.80
2024-01-01 22:45:00+00:00  1.10426  1.10447  1.10423  1.10438  237.60
2024-01-01 23:00:00+00:00  1.10446  1.10446  1.10383  1.10383  723.94

In [49]:
def ATR_POSITION_SIZER(account, risk_percent, multiplier):
    gbpusd_rate = 1.32
    TR1 = df['high'] - df['low']
    TR2 = (df['high'] - df['close'].shift(1)).abs()
    TR3 = (df['low'] - df['close'].shift(1)).abs()
    TR = pd.concat([TR1, TR2, TR3], axis =1).max(axis=1)
    ATR = TR.rolling(window=14).mean()
    df['ATR'] = TR.rolling(window=14).mean()
    stop_price = ATR * multiplier
    stop_distance = stop_price / 0.0001

    risk_budget = account * (risk_percent/100)
    risk_budget_usd = risk_budget * gbpusd_rate
    lots = risk_budget_usd / (stop_distance * 10)

    return lots, stop_distance

In [50]:
result = ATR_POSITION_SIZER(10000, 1, 2)
print(result)

(timestamp
2024-01-01 22:00:00+00:00         NaN
2024-01-01 22:15:00+00:00         NaN
2024-01-01 22:30:00+00:00         NaN
2024-01-01 22:45:00+00:00         NaN
2024-01-01 23:00:00+00:00         NaN
                               ...
2024-05-31 19:45:00+00:00    1.623902
2024-05-31 20:00:00+00:00    1.661871
2024-05-31 20:15:00+00:00    1.711111
2024-05-31 20:30:00+00:00    1.740113
2024-05-31 20:45:00+00:00    1.664865
Length: 10464, dtype: float64, timestamp
2024-01-01 22:00:00+00:00         NaN
2024-01-01 22:15:00+00:00         NaN
2024-01-01 22:30:00+00:00         NaN
2024-01-01 22:45:00+00:00         NaN
2024-01-01 23:00:00+00:00         NaN
                               ...
2024-05-31 19:45:00+00:00    8.128571
2024-05-31 20:00:00+00:00    7.942857
2024-05-31 20:15:00+00:00    7.714286
2024-05-31 20:30:00+00:00    7.585714
2024-05-31 20:45:00+00:00    7.928571
Length: 10464, dtype: float64)

In [51]:
df['EMA10'] = df['close'].ewm(span=10, adjust=False).mean()
df['EMA30'] = df['close'].ewm(span=30, adjust=False).mean()

df['signal'] = (df['EMA10'] > df['EMA30']).astype(int)
df['lag_signal'] = df['signal'].shift(1)

df.head(50)

,open,high,low,close,volume,ATR,EMA10,EMA30,signal,lag_signal
timestamp,,,,,,,,,,
2024-01-01 22:00:00+00:00,1.10427,1.10433,1.10423,1.10431,274.55,NaN,1.104310,1.104310,0,NaN
2024-01-01 22:15:00+00:00,1.10430,1.10434,1.10420,1.10430,143.55,NaN,1.104308,1.104309,0,0.0
2024-01-01 22:30:00+00:00,1.10431,1.10437,1.10431,1.10433,163.80,NaN,1.104312,1.104311,1,0.0
2024-01-01 22:45:00+00:00,1.10426,1.10447,1.10423,1.10438,237.60,NaN,1.104324,1.104315,1,1.0
2024-01-01 23:00:00+00:00,1.10446,1.10446,1.10383,1.10383,723.94,NaN,1.104235,1.104284,0,1.0
2024-01-01 23:15:00+00:00,1.10383,1.10383,1.10370,1.10376,756.69,NaN,1.104148,1.104250,0,0.0
2024-01-01 23:30:00+00:00,1.10376,1.10383,1.10361,1.10367,634.39,NaN,1.104061,1.104213,0,0.0
2024-01-01 23:45:00+00:00,1.10367,1.10373,1.10356,1.10365,989.44,NaN,1.103987,1.104176,0,0.0
2024-01-02 00:00:00+00:00,1.10366,1.10380,1.10366,1.10371,773.02,NaN,1.103936,1.104146,0,0.0
2024-01-02 00:15:00+00:00,1.10372,1.10373,1.10342,1.10346,638.60,NaN,1.103850,1.104102,0,0.0
2024-01-02 00:30:00+00:00,1.10346,1.10358,1.10345,1.10357,751.68,NaN,1.103799,1.104068,0,0.0
2024-01-02 00:45:00+00:00,1.10357,1.10383,1.10357,1.10381,1681.05,NaN,1.103801,1.104051,0,0.0
2024-01-02 01:00:00+00:00,1.10380,1.10432,1.10375,1.10388,2172.12,NaN,1.103815,1.104040,0,0.0
2024-01-02 01:15:00+00:00,1.10387,1.10431,1.10386,1.10393,1909.60,0.000255,1.103836,1.104033,0,0.0
2024-01-02 01:30:00+00:00,1.10394,1.10397,1.10369,1.10382,1694.88,0.000268,1.103833,1.104019,0,0.0
2024-01-02 01:45:00+00:00,1.10383,1.10399,1.10342,1.10348,1441.92,0.000299,1.103769,1.103984,0,0.0
2024-01-02 02:00:00+00:00,1.10347,1.10359,1.10314,1.10318,1357.31,0.000326,1.103662,1.103932,0,0.0
2024-01-02 02:15:00+00:00,1.10317,1.10317,1.10262,1.10262,1554.62,0.000349,1.103472,1.103848,0,0.0
2024-01-02 02:30:00+00:00,1.10265,1.10268,1.10221,1.10236,3324.66,0.000337,1.103270,1.103752,0,0.0
2024-01-02 02:45:00+00:00,1.10237,1.10240,1.10182,1.10187,3106.69,0.000369,1.103016,1.103630,0,0.0
2024-01-02 03:00:00+00:00,1.10187,1.10236,1.10176,1.10222,1504.70,0.000396,1.102871,1.103539,0,0.0
2024-01-02 03:15:00+00:00,1.10222,1.10240,1.10206,1.10213,1159.62,0.000409,1.102736,1.103448,0,0.0
2024-01-02 03:30:00+00:00,1.10216,1.10230,1.10206,1.10230,630.41,0.000415,1.102657,1.103374,0,0.0
2024-01-02 03:45:00+00:00,1.10231,1.10247,1.10231,1.10245,808.74,0.000405,1.102619,1.103315,0,0.0
2024-01-02 04:00:00+00:00,1.10245,1.10250,1.10207,1.10218,852.62,0.000426,1.102539,1.103242,0,0.0
2024-01-02 04:15:00+00:00,1.10222,1.10224,1.10192,1.10192,652.07,0.000431,1.102427,1.103156,0,0.0
2024-01-02 04:30:00+00:00,1.10194,1.10204,1.10173,1.10174,1265.05,0.000412,1.102302,1.103065,0,0.0
2024-01-02 04:45:00+00:00,1.10174,1.10211,1.10165,1.10208,1419.30,0.000413,1.102262,1.103001,0,0.0
2024-01-02 05:00:00+00:00,1.10208,1.10252,1.10208,1.10250,1106.46,0.000424,1.102305,1.102969,0,0.0
2024-01-02 05:15:00+00:00,1.10254,1.10281,1.10247,1.10265,1288.48,0.000408,1.102368,1.102948,0,0.0
2024-01-02 05:30:00+00:00,1.10265,1.10303,1.10265,1.10300,1235.90,0.000403,1.102483,1.102952,0,0.0
2024-01-02 05:45:00+00:00,1.10301,1.10335,1.10292,1.10333,1293.43,0.000394,1.102637,1.102976,0,0.0
2024-01-02 06:00:00+00:00,1.10334,1.10342,1.10316,1.10322,1386.14,0.000379,1.102743,1.102992,0,0.0
2024-01-02 06:15:00+00:00,1.10322,1.10337,1.10300,1.10320,1395.21,0.000364,1.102826,1.103005,0,0.0
2024-01-02 06:30:00+00:00,1.10320,1.10347,1.10309,1.10335,1875.64,0.000348,1.102921,1.103028,0,0.0
2024-01-02 06:45:00+00:00,1.10336,1.10351,1.10268,1.10286,2404.84,0.000383,1.102910,1.103017,0,0.0
2024-01-02 07:00:00+00:00,1.10286,1.10310,1.10245,1.10281,3423.25,0.000412,1.102892,1.103003,0,0.0
2024-01-02 07:15:00+00:00,1.10280,1.10377,1.10276,1.10372,2101.89,0.000472,1.103042,1.103050,0,0.0
2024-01-02 07:30:00+00:00,1.10371,1.10380,1.10298,1.10299,2426.75,0.000500,1.103033,1.103046,0,0.0
2024-01-02 07:45:00+00:00,1.10299,1.10314,1.10151,1.10153,6047.71,0.000594,1.102760,1.102948,0,0.0
2024-01-02 08:00:00+00:00,1.10156,1.10387,1.10156,1.10323,7312.72,0.000739,1.102845,1.102966,0,0.0
2024-01-02 08:15:00+00:00,1.10321,1.10341,1.10276,1.10288,4021.97,0.000752,1.102851,1.102961,0,0.0
2024-01-02 08:30:00+00:00,1.10288,1.10329,1.10280,1.10291,3860.83,0.000756,1.102862,1.102957,0,0.0
2024-01-02 08:45:00+00:00,1.10293,1.10329,1.10253,1.10295,4676.10,0.000786,1.102878,1.102957,0,0.0
2024-01-02 09:00:00+00:00,1.10296,1.10363,1.10289,1.10352,4678.27,0.000811,1.102995,1.102993,1,0.0
2024-01-02 09:15:00+00:00,1.10351,1.10378,1.10331,1.10332,2626.63,0.000814,1.103054,1.103014,1,1.0
2024-01-02 09:30:00+00:00,1.10332,1.10351,1.10189,1.10196,3565.53,0.000911,1.102855,1.102946,0,1.0
2024-01-02 09:45:00+00:00,1.10194,1.10199,1.10107,1.10150,4884.92,0.000951,1.102609,1.102853,0,0.0
2024-01-02 10:00:00+00:00,1.10149,1.10170,1.09970,1.10000,5377.62,0.001066,1.102134,1.102669,0,0.0
2024-01-02 10:15:00+00:00,1.09999,1.10055,1.09994,1.10039,4709.54,0.001051,1.101817,1.102522,0,0.0

In [55]:
in_trade = False
entry_price = None
stop_price = None
current_day = None
daily_r = 0.0
daily_limit = -3.0


trades = []

for i in range(len(df)): 
    row = df.iloc[i]
    signal =(row['lag_signal'])
    price = row['close']
    bar_day = df.index[i].date()
    if bar_day != current_day:
        current_day = bar_day
        daily_r = 0.0

    if not in_trade and signal == 1 and not pd.isna(row['ATR']) and daily_r > daily_limit:
        in_trade = True
        entry_price = price
        atr = row['ATR']
        stop_price = entry_price - (atr * 2)
    elif in_trade == True:
        if row['low'] <= stop_price: 
            r_outcome = -1.0
            trades.append(r_outcome)
            daily_r += r_outcome
            in_trade = False
        elif signal == 0:
            exit_price = price
            profit = exit_price - entry_price
            risk_perunit = entry_price - stop_price
            r_outcome = profit / risk_perunit
            trades.append(r_outcome)
            daily_r += r_outcome
            in_trade = False

In [56]:
print('Number of trades:', len(trades))
print('all R outcomes:', trades[:10])

Number of trades: 239
all R outcomes: [-1.0, -1.0, np.float64(-0.14078841512475102), np.float64(2.79123173277682), -1.0, np.float64(-0.43032786885249036), np.float64(-0.09016393442618326), -1.0, np.float64(0.056338028169071346), -1.0]

In [57]:
import numpy as np 

trades_array = np.array(trades)
print('Number of trades: ', len(trades_array))
print('Total R value: ', trades_array.sum())
print('R expectancy: ', trades_array.mean())
print('Win rate: ', (trades_array > 0).mean())

Number of trades:  239
Total R value:  3.157851079154078
R expectancy:  0.01321276602156518
Win rate:  0.30962343096234307